server.port: 5000

spring:
  application:
    name: api--fiap-cloud-development-trabalho
  data:
    mongodb:
      database: fiap
      uri: ${MONGODB_URI}
  jms:
    servicebus:
      connection-string: ${SERVICEBUS_URI}
      idle-timeout: 120000
      pricing-tier: Standard

management:
  endpoints:
    web:
      cors:
        allowed-headers: '*'
        allowed-methods: '*'
        allowed-origins: '*'
        exposed-headers: "Access-Control-Allow-Origin,Origin"
        allow-credentials: false
